### ISSUE TITLE
Right side scrollbar

### ISSUE THREAD

**Issue by jerone** [piroor/tst-active-tab-on-scrollbar#1]
I've enabled my scrollbar on the right side via [custom CSS](https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#show-scrollbar-in-the-tab-bar-rightside-1362). 
This however does not work with this extension. 
To fix that, I've added the following CSS:
```css
/* Show active-tab-on-scrollbar on the right side. 
https://github.com/piroor/tst-active-tab-on-scrollbar/issues/1 */
#tabbar.overflow .tabs::after {
  right: 0;
  left: unset;
}
```

![image](https://user-images.githubusercontent.com/55841/190202809-0881bd5c-783e-4ec0-9a61-9dcde541ea86.png)

Also mentioned by someone else on Mozilla Addons page: https://addons.mozilla.org/en-US/firefox/addon/tst-active-tab-on-scroll-bar/reviews/1861575/
